apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: kustomize-flux-app
  namespace: default
spec:
  interval: 1m
  targetNamespace: default
  sourceRef:
    kind: GitRepository
    name: source-demo-flux-app
  path: "./manifests"
  prune: true
  timeout: 1m