apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hello-world
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: hello-world
    spec:
      containers:
        - name: hello-world
          image: ghcr.io/jeremie-koster/demo-flux-app:0.0.1 # {"$imagepolicy": "default:demo-image-policy"}
          ports:
            - containerPort: 5000
